<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>AdminForge</PackageId>
    <Version>0.0.1</Version>
    <Description>Automatic admin panel generator for ASP.NET Core applications.</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../AdminForge.Core/AdminForge.Core.csproj" />
    <ProjectReference Include="../AdminForge.DataAccess.EfCore/AdminForge.DataAccess.EfCore.csproj" />
    <ProjectReference Include="../AdminForge.LiveUpdates/AdminForge.LiveUpdates.csproj" />
    <ProjectReference Include="../AdminForge.UI.Blazor/AdminForge.UI.Blazor.csproj" />
    <ProjectReference Include="../AdminForge.Middleware/AdminForge.Middleware.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(IsPackable)' == 'true'">
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
