<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <RootNamespace>AdminForge.UI.Blazor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AdminForge.Core/AdminForge.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="MudBlazor" />
  </ItemGroup>
</Project>
