<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>AdminForge.DataAccess.EfCore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AdminForge.Core/AdminForge.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
</Project>
